# Tensor Exercises

Use this notebook to practice the tensor topics from `README.md` and `01-tensors/README.md`.

For each exercise:

- Write code in the empty code cell.
- Print tensor shapes often.
- Inspect `.dtype` and `.device` when relevant.
- Write a short note about what confused you or what you learned.

In [6]:
import torch

torch.manual_seed(42)
torch.set_default_device('mps')

## Exercise 1: Create Tensors From Python Lists

Create the following tensors from Python lists:

1. A scalar tensor containing `7`.
2. A vector tensor containing `[1, 2, 3, 4]`.
3. A 2D matrix tensor with shape `(2, 3)`.

Print each tensor and its `.shape`.

In [7]:
st = torch.tensor(7)
vt = torch.tensor([1, 2, 3, 4])
mt = torch.rand((2, 3,))

print(st, st.shape, st.device)
print(vt, vt.shape, vt.device)
print(mt, mt.shape, mt.device)

tensor(7, device='mps:0') torch.Size([]) mps:0
tensor([1, 2, 3, 4], device='mps:0') torch.Size([4]) mps:0
tensor([[0.8172, 0.5881, 0.5581],
        [0.7691, 0.3394, 0.4560]], device='mps:0') torch.Size([2, 3]) mps:0


Notes:

- What confused me:
- What I learned:
- One thing I want to inspect deeper:

## Exercise 2: Random, Zeros, Ones, And Range Tensors

Create these tensors:

1. A random tensor with shape `(3, 4)`.
2. A zeros tensor with shape `(2, 5)`.
3. A ones tensor with shape `(4,)`.
4. A range tensor containing values from `0` to `9`.

Print each tensor, its shape, and its dtype.

In [9]:
t1 = torch.rand((3, 4,))
t2 = torch.zeros((2, 5,))
t3 = torch.ones((4,))
t4 = torch.arange(0, 9)

print(t1, t1.shape, t1.dtype, t1.device)
print(t2, t2.shape, t2.dtype, t2.device)
print(t3, t3.shape, t3.dtype, t3.device)
print(t4, t4.shape, t4.dtype, t4.device)

tensor([[0.5880, 0.2433, 0.5797, 0.6805],
        [0.5575, 0.3254, 0.4291, 0.2087],
        [0.0562, 0.2676, 0.1369, 0.5249]], device='mps:0') torch.Size([3, 4]) torch.float32 mps:0
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], device='mps:0') torch.Size([2, 5]) torch.float32 mps:0
tensor([1., 1., 1., 1.], device='mps:0') torch.Size([4]) torch.float32 mps:0
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8], device='mps:0') torch.Size([9]) torch.int64 mps:0


## Exercise 3: Inspect Tensor Metadata

Create one integer tensor and one floating-point tensor. For both tensors, print:

1. `.shape`
2. `.dtype`
3. `.device`
4. `.ndim`

Question: Why might dtype matter when training a model?

In [10]:
int_tensor = torch.tensor(3)
float_tensor = torch.tensor(3.0)

print(int_tensor, int_tensor.shape, int_tensor.dtype, int_tensor.device, int_tensor.ndim)
print(float_tensor, float_tensor.shape, float_tensor.dtype, float_tensor.device, float_tensor.ndim)

tensor(3, device='mps:0') torch.Size([]) torch.int64 mps:0 0
tensor(3., device='mps:0') torch.Size([]) torch.float32 mps:0 0


Answer:


## Exercise 4: Indexing And Slicing

Start with this tensor:

```python
x = torch.arange(1, 13).reshape(3, 4)
```

Write code to select:

1. The first row.
2. The last column.
3. The value `7`.
4. The 2x2 block in the bottom-right corner.

Print the shape of each selection.

In [11]:
x = torch.arange(1, 13).reshape(3, 4)
x

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], device='mps:0')

In [16]:
print(x[0])
print(x[-1][-1])
print(x[1][2])
print(x[-2:, -2:])

tensor([1, 2, 3, 4], device='mps:0')
tensor(12, device='mps:0')
tensor(7, device='mps:0')
tensor([[ 7,  8],
        [11, 12]], device='mps:0')


## Exercise 5: Broadcasting

Create:

```python
a = torch.ones(3, 4)
b = torch.arange(4)
```

Questions:

1. What is the shape of `a + b`?
2. Why does this operation work?
3. Create another tensor `c` where `a + c` works by broadcasting across rows instead of columns.

In [21]:
a = torch.ones(3, 4)
b = torch.arange(4)
c = torch.ones(3, 1)
a + b, a + c, c

(tensor([[1., 2., 3., 4.],
         [1., 2., 3., 4.],
         [1., 2., 3., 4.]], device='mps:0'),
 tensor([[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]], device='mps:0'),
 tensor([[1.],
         [1.],
         [1.]], device='mps:0'))

Answer:


## Exercise 6: Broadcasting Error

Create two tensors with shapes `(3, 4)` and `(3,)`. Try to add them.

Questions:

1. What error do you get?
2. How can you reshape one tensor so the addition works?
3. What is the final output shape?

In [23]:
a = torch.ones(3, 4)
b = torch.ones(4,)
a + b

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]], device='mps:0')

Answer:


## Exercise 7: Matrix Multiplication

Create two tensors `A` and `B` where matrix multiplication is valid. Use both `A @ B` and `torch.matmul(A, B)`.

Questions:

1. What are the shapes of `A` and `B`?
2. What is the output shape?
3. Why would `torch.randn(2, 3) @ torch.randn(2, 3)` fail?

In [25]:
A = torch.arange(12).reshape(3, 4)
B = torch.arange(12).reshape(4, 3)
A, B, A @ B, torch.matmul(A, B)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]], device='mps:0'),
 tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]], device='mps:0'),
 tensor([[ 42,  48,  54],
         [114, 136, 158],
         [186, 224, 262]], device='mps:0'),
 tensor([[ 42,  48,  54],
         [114, 136, 158],
         [186, 224, 262]], device='mps:0'))

Answer:


## Exercise 8: `view` Versus `reshape`

Start with:

```python
x = torch.arange(12)
```

Tasks:

1. Convert `x` to shape `(3, 4)` using `view`.
2. Convert `x` to shape `(2, 6)` using `reshape`.
3. Try to convert `x` to shape `(5, 3)`.

Question: Why does one of these shape conversions fail?

In [32]:
x = torch.arange(12)
x.view(3, 4), x.reshape(2, 6)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]], device='mps:0'),
 tensor([[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]], device='mps:0'))

Answer:


## Exercise 9: Transpose And Permute

Create a tensor with shape `(2, 3, 4)`.

Tasks:

1. Use `transpose` to swap dimensions `1` and `2`.
2. Use `permute` to reorder dimensions from `(2, 3, 4)` to `(4, 2, 3)`.
3. Print the shape after each operation.

Question: When might `permute` be useful for image data?

In [33]:
x = torch.rand(2, 3, 4)
x

tensor([[[0.6543, 0.4484, 0.3422, 0.5188],
         [0.5544, 0.1488, 0.1078, 0.1464],
         [0.1069, 0.8505, 0.2788, 0.7084]],

        [[0.7732, 0.2056, 0.1076, 0.1377],
         [0.9927, 0.4017, 0.6543, 0.5096],
         [0.2001, 0.8022, 0.3656, 0.6411]]], device='mps:0')

Answer:


## Exercise 10: Unsqueeze And Squeeze

Start with a vector tensor of shape `(5,)`.

Tasks:

1. Use `unsqueeze` to make it shape `(1, 5)`.
2. Use `unsqueeze` to make it shape `(5, 1)`.
3. Use `squeeze` to remove dimensions of size `1`.

Question: Why are extra dimensions useful when working with batches?

Answer:


## Exercise 11: Device Movement

Check whether `mps` is available on your Mac. Create a tensor and move it to `mps` if available. Otherwise, keep it on CPU.

Questions:

1. What device is your tensor on?
2. What happens if you try to add tensors that are on different devices?
3. Why is device placement important when training models?

In [ ]:
device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
device

Answer:


## Exercise 12: Mini Challenge

Pretend you have a batch of 8 samples. Each sample has 4 input features.

Tasks:

1. Create an input tensor `X` with shape `(8, 4)`.
2. Create a weight tensor `W` with shape `(4, 3)`.
3. Create a bias tensor `b` with shape `(3,)`.
4. Compute `Y = X @ W + b`.
5. Print the shapes of `X`, `W`, `b`, and `Y`.

Questions:

1. What does each dimension represent?
2. Why does adding `b` work?
3. How is this related to a linear layer in a neural network?

Answer:


## Final Reflection

Write your summary after finishing the notebook.

```text
What confused me:
What I learned:
One thing I want to inspect deeper:
```